### ISSUE TITLE
[Communication] Wire up a button to initiate an SMS message

### ISSUE THREAD

**Issue by xfrehner12** [cs481-ekh/f21-welolo#24]
There is currently a payment page on our website. We need to wire up the submit payment button to send all payment information in JSON format to our backend server at some endpoint.  The entire form must be filled out properly before allowing an SMS to be sent.

This endpoint should not do anything with the payment data, but rather just log it at the console to show that it is being sent properly. The phone number will be used to initiate the SMS messaging process

**Comment by AlyssaRWest** [comment]
Ended up being implemented in #23
